name: CD

on: workflow_call

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
    
    - name: Get ECS Task Definition
      run: |
        aws ecs describe-task-definition \
        --task-definition task-ci-cd-practice \
        --query taskDefinition > task-definition.json

    # Copy task-definition.json to an .old file
    - name: Task Definition Backup
      run: cp task-definition.json{,.old}
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: task-ci-cd-practice-app
        image: |-
          ghcr.io/xurlz/go_ci:${{ case(
            github.event_name == 'pull_request',
              format('{0}-{1}',github.head_ref,github.run_number),
            github.ref_name
          ) }}
        environment-variables: |
          HOST=${{ secrets.DB_HOST }}
          USER=${{ secrets.DB_USER }}
          PASSWORD=${{ secrets.DB_PASSWORD }}
          DBNAME=${{ secrets.DB_NAME }}
          DBPORT=${{ secrets.DB_PORT }}
          PORT=8000
          
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: service-task-ci-cd-practice
        cluster: cluster-ci-cd-practice
        wait-for-service-stability: true

    - name: Request
      run: sleep 30; curl -fSsL http://ldbal-ci-cd-practice-1393171223.sa-east-1.elb.amazonaws.com:8080/teapot
      continue-on-error: true


